### ISSUE TITLE
Can I use ASAP on my own computer?

### ISSUE THREAD

**Issue by Yoon-Seob-Kim** [DeplanckeLab/ASAP#1]
Hello

I work on melanoma single cell RNAseq data  (5k)

I think that ASAP is the greatest application, but slow analysis is shortcoming on the web

Can I use ASAP on my own computer?

**Comment by DeplanckeLab** [comment]
Hi,

I don't think that the time needed for processing the data is currently much slower than on a local computer, if you use the same algorithms/methods. But we are currently working on accelerating the analysis on the server by different means.  For e.g. we are looking for faster algorithms/approaches to process the larger scale data faster.

In the meantime, we are also generating a Docker to allow any user to have a standalone install of ASAP on their own server/computer.

In the meantime, you are also welcome to use any files available on github to generate your own install. But we understand that this process can be cumbersome, and that's why we are preparing a Docker install.

Cheers

**Comment by kysbbubbu** [comment]
Hi, Thank you for your fast response

All process is relatively fast, but TSNE process needs relatively long time (around 1 hr)

Especially when I want to evaluate various parameteres of filtering, normalization, and perplexity of TSNE

It takes several yours to do so.

I think that ASAP development version was build on the platform of ruby on rails 

As you mentioned, i experienced some troubles on installing and open it in my own computer.

I will wait for standalone install of ASAP

Thank you!

**Comment by DeplanckeLab** [comment]
Hi,

We recently released a [Docker install](https://github.com/fabdavid/asap2_web) of ASAP in case you want to install it on your own computer.
It is still in beta, but you can leave any comments in the corresponding GitHub project if it does not work on your machine.

FYI a new release of ASAP will be out soon, and should be much faster than the previous version.

Cheers
