### ISSUE TITLE
Is ASAP still actively maintained?

### ISSUE THREAD

**Issue by farshadf** [DeplanckeLab/ASAP#2]
Hi,

I do not see any activity on ASAP development for the past 17 months and the asap website is not updated recently as well. Is this tool still maintained by Deplancke group?

Thanks.

**Comment by VincentGardeux** [comment]
Hi @farshadf

**Comment by VincentGardeux** [comment]
Hi again @farshadf 

So we tested the current repos and Dockers and indeed there are some adaptations to make in order to properly install everything on a local machine.
Basically, the current architecture relies on two Dockers, one for the R/Python scripts (that we called asap_run) and one for the web server (that we called asap_web).

However, we are currently working on modifying this architecture, to one Docker architecture. 
So we will not be able to debug the previous installation procedure. But we'll work on a much more detailed "local installation" procedure for the new architecture, so it's easier to install for anyone who wants to install ASAP locally.

Hopefully, we will have more vision by the beginning of next year.

Cheers
